name: config
alias: c
help: Configure workspace. Applications needs to be already installed. Some of steps require interactive input, so this command cannot be used in CI/CD environments and automation scripts.
args:
- name: application
  help: >
    Application or toolkit needs to be configured.
  allowed: [all, git, kubeconfig, vals]
    
examples:
- workspace config git // Configure git toolkit
- workspace config all // Configure all applications
