name: Static Analysis
on:
  pull_request:
  push: { branches: master }
  workflow_dispatch:
jobs:
  static_analysis:
    name: Run shellcheck

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Run ShellCheck
      uses: ludeeus/action-shellcheck@master
      with:
        ignore_paths: >-
          release
          src/send_completions.sh
          src/functions/colors.sh
        severity: error
